const movies = [
  {
    id: "1000",
    titulo: "El Padrino",
    anioLanzamiento: 1972,
    descripcion: "La saga de 'El Padrino' sigue la vida de una poderosa familia de mafiosos liderada por Don Vito Corleone, un patriarca respetado y temido en el mundo del crimen organizado. Su hijo Michael, inicialmente reacio a involucrarse en los asuntos familiares, se ve arrastrado hacia el legado de su padre y se convierte en una figura clave en la organización. La película explora la complejidad de las relaciones familiares y los dilemas morales que enfrenta Michael mientras se sumerge cada vez más en la vida del crimen.",
    tipo: "pelicula",
    url: "https://ca-times.brightspotcdn.com/dims4/default/2314d53/2147483647/strip/true/crop/2093x3000+0+0/resize/1200x1720!/quality/80/?url=https%3A%2F%2Fcalifornia-times-brightspot.s3.amazonaws.com%2F47%2F95%2Fcbf137037b833a53a724fde3f53e%2Fcfdj8emgq7504ddbn1ibedbziqes-ufxmz-ypi0gordml8oigvx-qxnfyjdexxje48b9jsnhzr2hbbtg9-5bm2ewo-sfvcb9svtpufonjqohy-raixysjlgk7fagt3voiify9grgz0pkj-sysmn1pfblqffyiedjz8nszvhrheowg2imuyrmeklodsplgwx3wmznmclm-gx-cvc7m0lf7h7crd5meu1oztvsd9po-e1pldrzmjwobcwk9h7avlf0y4ew56xkel9filhfyidkf9rpndq4ic7-snlvnin85poimejwzyp6rq-q8qsqvmlvl2xaq3rsy-7axvtxqcpqinvjubaglw5risa6bqkfrpqowvdt29rhgoxnbsbi3dnwzldfjuimuizsg2hody3cu-y1kgk",
    genero: ["comedia", "terror"],
    duracion: "2:30",
    calificacion: 6,
    trailer: "v72XprPxy3E"
  },
  {
    id: "1001",
    titulo: "Volver al Futuro",
    anioLanzamiento: 1985,
    descripcion: "Volver al Futuro cuenta la emocionante historia de Marty McFly, un joven que viaja accidentalmente en el tiempo a través de un DeLorean modificado por su excéntrico amigo Doc Brown. Marty se encuentra en el pasado y debe asegurarse de que sus padres se enamoren para asegurar su propia existencia en el futuro. La película combina elementos de ciencia ficción, aventura y romance mientras Marty intenta encontrar una manera de volver a casa mientras evita alterar el curso de la historia.",
    tipo: "pelicula",
    url: "https://www.tematika.com/media/catalog/Ilhsa/Imagenes/638724.jpg",
    genero: ["ficción", "romance"],
    duracion: "2:30",
    calificacion: 8,
    trailer: "25vkwSdtLdk"
  },
  {
    id: "1002",
    titulo: "Titanic",
    anioLanzamiento: 1997,
    descripcion: "Titanic es un romance épico situado en el trágico contexto del hundimiento del RMS Titanic. La película sigue la historia de amor entre Jack, un artista bohemio, y Rose, una joven adinerada comprometida con un hombre de negocios arrogante. A bordo del majestuoso Titanic, Jack y Rose viven una apasionada historia de amor que se enfrenta a los desafíos del destino y la tragedia. La película mezcla el romance con el impresionante telón de fondo del famoso naufragio del Titanic, creando una experiencia cinematográfica emotiva y cautivadora.",
    tipo: "pelicula",
    url: "https://www.abc.es/media/peliculas/000/044/428/titanic-1.jpg",
    genero: ["romance"],
    duracion: "2:30",
    calificacion: 9,
    trailer: "tA_qMdzvCvk"
  },
  {
    id: "1003",
    titulo: "El Señor de los Anillos: La Comunidad del Anillo",
    anioLanzamiento: 2001,
    descripcion: "Basada en la obra literaria de J.R.R. Tolkien, El Señor de los Anillos: La Comunidad del Anillo sigue la aventura de un hobbit llamado Frodo Baggins, quien debe llevar un anillo malévolo hasta las llamas del Monte del Destino para destruirlo y evitar que caiga en manos del malvado Sauron. En compañía de un variado grupo de personajes, incluyendo elfos, enanos, humanos y otros hobbits, Frodo enfrenta peligros y desafíos mientras el destino de la Tierra Media descansa en sus hombros.",
    tipo: "pelicula",
    url: "https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2016/12/senor-anillos-retorno-rey.jpg",
    genero: ["fantasia", "ficción"],
    duracion: "2:30",
    calificacion: 6.3,
    trailer: "3GJp6p_mgPo"
  },
  {
    id: "1004",
    titulo: "La La Land",
    anioLanzamiento: 2016,
    descripcion: "La La Land es un deslumbrante musical que narra la historia de Mia, una aspirante a actriz, y Sebastian, un apasionado pianista de jazz, mientras persiguen sus sueños en la ciudad de Los Ángeles. A través de números musicales cautivadores, la película celebra el amor, la ambición y la creatividad mientras los protagonistas enfrentan las dificultades de perseguir sus objetivos artísticos y mantener una relación en una ciudad que desafía sus sueños.",
    tipo: "pelicula",
    url: "https://musicart.xboxlive.com/7/b7e43e00-0000-0000-0000-000000000002/504/image.jpg?w=1920&h=1080",
    genero: ["romance", "aventura", "drama"],
    duracion: "2:30",
    calificacion: 9,
    trailer: "45s24h98iOc"
  },
  {
    id: "1005",
    titulo: "Avengers: Endgame",
    anioLanzamiento: 2019,
    descripcion: "Avengers: Endgame es el épico enfrentamiento final entre los héroes del universo Marvel y el temible villano Thanos. La película sigue a los Vengadores mientras buscan la forma de deshacer los devastadores efectos del chasquido de Thanos, que ha eliminado a la mitad de la población del universo. Con acción espectacular y giros sorprendentes, la película es un emocionante desenlace de la saga de los Vengadores.",
    tipo: "pelicula",
    url: "https://lumiere-a.akamaihd.net/v1/images/690x0w_f1b0509a.jpeg?region=0%2C0%2C690%2C1035",
    genero: ["fantasia", "ficción", "aventura"],
    duracion: "2:30",
    calificacion: 7.3,
    trailer: "PyakRSni-c0"
  },
  {
    id: "1006",
    titulo: "Barbie",
    anioLanzamiento: 2023,
    descripcion: "Barbie es una película de aventuras y fantasía basada en la popular muñeca del mismo nombre. La historia sigue a Barbie, quien vive en Barbieland, un mundo perfecto y mágico. Sin embargo, cuando es expulsada al mundo real por no ser considerada lo suficientemente perfecta, se embarca en una emocionante aventura para descubrir su verdadero potencial y aprender la importancia de ser auténtica y fiel a sí misma.",
    tipo: "pelicula",
    url: "https://elcomercio.pe/resizer/sjdQp0NvLtsRndrAP2Ec05gQcho=/980x0/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/WZTVEL3PIBA4JPH4XZMIVP2EUM.jpg",
    genero: ["Comedia", "Aventura", "Fantasía"],
    duracion: "1h 40min",
    calificacion: 7.8,
    trailer: "zh4KhVSMwtQ"
  },
  {
    id: "1007",
    titulo: "Proyecto Extracción",
    anioLanzamiento: 2023,
    descripcion: "Proyecto Extracción es una película de acción y suspenso que sigue a dos veteranos de guerra asignados con la misión de escoltar a un grupo de civiles a través de la peligrosa autopista de la muerte en Baghdad hasta llegar a la segura Zona Verde. La película explora temas de valentía, lealtad y sacrificio mientras los personajes enfrentan peligros mortales para cumplir su misión.",
    tipo: "pelicula",
    url: "https://depor.com/resizer/bCymfasxw3OGEQRsVRdF4zz0x1M=/620x0/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/JFLE736KTBDVJFGCD3ZDXGUQW4.png",
    genero: ["Acción", "Aventura", "Suspenso"],
    duracion: "2:30",
    calificacion: 7.3,
    trailer: "QtAlwa0xmHg"
  },
  {
    id: "1008",
    titulo: "Misión de rescate",
    anioLanzamiento: 2020,
    descripcion: "Todo en todas partes al mismo tiempo cuenta la emocionante historia de Evelyn Wang, una inmigrante china que se ve envuelta en una aventura en la que debe explorar otros universos y conectarse con las vidas que podría haber llevado. La película explora temas de identidad, destino y el vasto potencial del multiverso, llevando a la protagonista a una aventura que trasciende las barreras del espacio y el tiempo.",
    tipo: "pelicula",
    url: "https://cuevana3.eu/_next/image?url=https%3A%2F%2Fimage.tmdb.org%2Ft%2Fp%2Foriginal%2FcNu6VozUfD9jjQUjGuGBRoMlpYA.jpg&w=256&q=75",
    genero: ["Acción", "Suspenso"],
    duracion: "2:30",
    calificacion: 7.4,
    trailer: "18fMBzX5PdA"
  },
  {
    id: "1009",
    titulo: "Todo en todas partes al mismo tiempo",
    anioLanzamiento: 2023,
    descripcion: "Evelyn Wang, una inmigrante china, se ve envuelta en una loca aventura en la que ella sola puede salvar el mundo explorando otros universos y conectándose con las vidas que podría haber llevado. Desafortunadamente, esto la lleva a una aventura aún más desafiante cuando se encuentra perdida en los mundos infinitos del multiverso.",
    tipo: "pelicula",
    url: "https://mx.web.img2.acsta.net/pictures/22/05/09/20/29/5744562.jpg",
    genero: ["Acción", "Suspenso"],
    duracion: "1h 56min",
    calificacion: 8.4,
    trailer: "qhOgSLBtKIE"
  },
  {
    id: "1010",
    titulo: "Efecto mariposa",
    anioLanzamiento: 2020,
    descripcion: "Efecto mariposa sigue la historia de Evan Treborn, un joven atormentado por dolorosos recuerdos de su infancia. Descubre que puede viajar atrás en el tiempo y decide utilizar esta habilidad para intentar cambiar su pasado traumático. Sin embargo, se da cuenta de que cada mínimo cambio en el pasado tiene consecuencias drásticas en su futuro, lo que lo lleva a enfrentar decisiones difíciles y dilemas éticos mientras lucha por encontrar la forma de redimir su pasado y construir un mejor futuro.",
    tipo: "pelicula",
    url: "https://pics.filmaffinity.com/El_efecto_mariposa-489365577-large.jpg",
    genero: ["Acción", "ficción"],
    duracion: "1h 56min",
    calificacion: 7.4,
    trailer: "9sAU7RkGHAk"
  },
  {
    id: "1011",
    titulo: "The truman show",
    anioLanzamiento: 2020,
    descripcion: "The Truman Show es una cautivadora película que sigue la vida de Truman Burbank, quien es la estrella involuntaria de un programa de televisión que lo ha estado filmando desde su nacimiento sin que él lo sepa. A medida que Truman comienza a sospechar que su vida no es lo que parece, comienza a cuestionar su realidad y emprende una búsqueda para descubrir la verdad detrás de su existencia altamente controlada. La película reflexiona sobre temas de libertad, identidad y el poder de los medios de comunicación en la sociedad moderna.",
    tipo: "pelicula",
    url: "https://i.pinimg.com/564x/25/f1/6c/25f16c89a72af7f17a735dc0505b0561.jpg",
    genero: ["Acción", "Suspenso"],
    duracion: "1h 56min",
    calificacion: 7.4,
    trailer: "bEmFm4G39Mk"
  },
  {
    id: "1012",
    titulo: "Diario de una pasión",
    anioLanzamiento: 2020,
    descripcion: "Diario de una pasión es un romántico drama que narra la conmovedora historia de Noah Calhoun y Allie Hamilton, dos jóvenes de diferentes ambientes sociales que se enamoran profundamente durante un verano inolvidable. Sin embargo, su amor se ve amenazado por la desaprobación de sus familias y los obstáculos del destino, incluyendo la guerra. A través de saltos en el tiempo, la película explora cómo el poder del amor verdadero puede superar las adversidades y perdurar a lo largo de los años.",
    tipo: "pelicula",
    url: "https://mx.web.img3.acsta.net/medias/nmedia/18/67/61/01/20070878.jpg",
    genero: ["romance", "Suspenso"],
    duracion: "1h 56min",
    calificacion: 7.4,
    trailer: "YYz8i3hmqWA"
  },
  {
    id: "1013",
    titulo: "Frozen",
    anioLanzamiento: 2020,
    descripcion: "Frozen es un encantador cuento de hadas moderno que sigue las aventuras de la princesa Anna, quien se embarca en un emocionante viaje para encontrar a su hermana Elsa, que se ha retirado a un palacio de hielo tras revelar sus poderes mágicos de hielo. La película celebra la importancia del amor fraternal y presenta un mensaje poderoso sobre la autoaceptación y la importancia de ser auténtico",
    tipo: "pelicula",
    url: "https://i.pinimg.com/originals/cc/1d/08/cc1d089897d53a1c3bbec368925fbc6f.jpg",
    genero: ["Acción", "Suspenso"],
    duracion: "1h 56min",
    calificacion: 7.4,
    trailer: "FmrnYJGQQug"
  },
  {
    id: "1014",
    titulo: "Up",
    anioLanzamiento: 2020,
    descripcion: "Up cuenta la emocionante historia de Carl Fredricksen, un viudo de 78 años que decide cumplir el sueño de su vida: elevar su casa con miles de globos y volar hacia América del Sur. Pero descubre que tiene un intrépido acompañante: Russell, un niño scout de 8 años. Juntos, emprenden una aventura llena de humor y emotividad, enfrentando desafíos inesperados mientras encuentran la verdadera amistad en el camino.",
    tipo: "pelicula",
    url: "https://pics.filmaffinity.com/Up-555653789-large.jpg",
    genero: ["Acción", "Suspenso"],
    duracion: "1h 56min",
    calificacion: 7.4,
    trailer: "qoZo9MiICo0"
  },
  {
    id: "1015",
    titulo: "Babylon",
    anioLanzamiento: 2023,
    descripcion: "Babylon es un drama ambientado en el Hollywood de los años veinte, que retrata la decadencia, depravación y excesos escandalosos que llevan al ascenso y caída de varios ambiciosos soñadores. La película explora las luces y sombras de la fama y la industria del cine mientras los personajes luchan por alcanzar el éxito y enfrentan los oscuros secretos que acechan en la meca del entretenimiento.",
    tipo: "pelicula",
    url: "https://public-assets-pressexpress.s3.amazonaws.com/assets/releases/docimages/2c154f64/BABYLON-PDATEANNOUNCEPRESSRELEASE-CLEAN_html_6408bba55dfb89c3.jpg",
    genero: ["Acción", "Suspenso"],
    duracion: "1h 08min",
    calificacion: 5.4,
    trailer: "gBil8RpweBE"
  },
  {
    id: "1016",
    titulo: "After",
    anioLanzamiento: 2018,
    descripcion: "After es un drama romántico que sigue la historia de Tessa Young, una joven universitaria cuya vida cambia drásticamente cuando conoce a Hardin Scott, un misterioso joven con un pasado turbulento. A medida que se enamoran, enfrentan numerosos desafíos y pruebas que ponen a prueba su relación y los obligan a enfrentar sus propias inseguridades. La película explora temas de amor, crecimiento personal y autodescubrimiento.",
    tipo: "pelicula",
    url: "https://www.eluniverso.com/resizer/ieyrzFWIVQPQwNqQm8IensTlb1A=/256x400/smart/filters:quality(70)/cloudfront-us-east-1.images.arcpublishing.com/eluniverso/KEUEU7RMT5CMREFUXSASUEDNSY.jpg",
    genero: ["romance", "drama"],
    duracion: "1h 40min",
    calificacion: 6.8,
    trailer: "3zjxECCWwrU"
  },
  {
    id: "1017",
    titulo: "Matrix",
    anioLanzamiento: 2006,
    descripcion: "Matrix es una película de ciencia ficción que sigue al programador informático Thomas Anderson, conocido como Neo, quien descubre que la realidad que cree conocer es una simulación creada por máquinas para mantener a la humanidad esclavizada. Un grupo de rebeldes liderado por Morfeo lo libera del engaño y lo recluta para luchar contra las máquinas y liberar a la humanidad. La película es un viaje emocionante y filosófico que explora conceptos de realidad, libre albedrío y el poder de la mente humana.",
    tipo: "pelicula",
    url: "https://wenythepooh.files.wordpress.com/2010/02/matrix_ver3.jpg",
    genero: ["Acción", "Suspenso"],
    duracion: "2h 20min",
    calificacion: 9.0,
    trailer: "OM0tSTEQCQA"
  },
];

export { movies }