const series = [
  {
    id: "2000",
    titulo: "Game of Thrones",
    anioLanzamiento: 2011,
    descripcion: "Intrigas y luchas por el poder entre familias nobles en los Siete Reinos de Westeros. La serie sigue múltiples tramas y personajes mientras se desarrolla una épica y violenta batalla por el Trono de Hierro. Con un mundo lleno de políticas, magia, traiciones y giros inesperados, Game of Thrones se convirtió en un fenómeno global, dejando una marca indeleble en la historia de la televisión.",
    tipo: "serie",
    url: "https://m.media-amazon.com/images/M/MV5BN2IzYzBiOTQtNGZmMi00NDI5LTgxMzMtN2EzZjA1NjhlOGMxXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_FMjpg_UX1000_.jpg",
    calificacion: 9.3,
    genero: ["Fantasy", "Drama"],
    duracion: "1h 14min",
    trailer: "KPLWWIOCOOQ"
  },
  {
    id: "2001",
    titulo: "Breaking Bad",
    anioLanzamiento: 2008,
    descripcion: "Walter White, un profesor de química de secundaria, recibe un devastador diagnóstico de cáncer terminal. Con su futuro y el de su familia en la balanza, Walter decide ingresar al mundo del narcotráfico para asegurar su legado financiero. Así, se convierte en el legendario narcotraficante conocido como 'Heisenberg', liderando una operación ilegal que lo llevará a situaciones cada vez más peligrosas y morales. Breaking Bad es un viaje oscuro y emocionante hacia los límites de la moralidad y la degradación humana.",
    tipo: "serie",
    url: "https://m.media-amazon.com/images/M/MV5BYmQ4YWMxYjUtNjZmYi00MDQ1LWFjMjMtNjA5ZDdiYjdiODU5XkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg",
    calificacion: 9.5,
    genero: ["Crimen", "Drama"],
    duracion: "49min",
    trailer: "HhesaQXLuRY"
  },
  {
    id: "2002",
    titulo: "Stranger Things",
    anioLanzamiento: 2016,
    descripcion: "En el pequeño pueblo de Hawkins, un grupo de niños se enfrenta a fenómenos sobrenaturales y aterradoras fuerzas desconocidas. Todo comienza cuando uno de ellos desaparece misteriosamente. Pronto, encuentran a una misteriosa niña con habilidades psíquicas llamada Eleven, que los lleva a descubrir un mundo paralelo lleno de monstruos y secretos gubernamentales. Stranger Things es una mezcla única de nostalgia de los años 80, ciencia ficción y horror que ha cautivado a audiencias de todas las edades.",
    tipo: "serie",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBfYF4iA8lIktTm6pvqM3joGZ45Kvi-48O1QrsIJIjgP70cZnd7FAryvNXv6s5oz2u8N0&usqp=CAU",
    calificacion: 8.7,
    genero: ["Drama", "Fantasy", "Horror"],
    duracion: "51min",
    trailer: "x7Yq9MJUqjY"
  },
  {
    id: "2003",
    titulo: "Friends",
    anioLanzamiento: 1994,
    descripcion: "Esta icónica serie sigue las vidas y amores de seis amigos en Nueva York: Rachel, Ross, Monica, Chandler, Joey y Phoebe. A través de risas, alegrías y lágrimas, el grupo enfrenta situaciones cómicas y emotivas mientras atraviesan las vicisitudes de la vida, el trabajo y las relaciones. Friends se ha convertido en un referente cultural y una de las comedias de situación más queridas y recordadas de todos los tiempos.",
    tipo: "serie",
    url: "https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2016/07/poster-friends.jpg?tf=1200x",
    calificacion: 8.5,
    genero: ["Comedy", "Romance"],
    duracion: "22min",
    trailer: "MfvvhM6IJS0"
  },
  {
    id: "2004",
    titulo: "The Crown",
    anioLanzamiento: 2016,
    descripcion: "The Crown narra la vida de la Reina Isabel II desde su boda en 1947 hasta los acontecimientos históricos que marcaron su reinado, explorando su relación con los primeros ministros, su familia y las dificultades inherentes de su papel como monarca. Con una cuidadosa atención al detalle histórico, esta serie dramática ofrece una visión fascinante de los entresijos de la realeza británica y los desafíos personales y públicos que enfrentó la monarca más longeva de la historia de Gran Bretaña.",
    tipo: "serie",
    url: "https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2018/03/crown-portada.jpg",
    calificacion: 8.6,
    genero: ["Biography", "Drama", "History"],
    duracion: "58min",
    trailer: "zzBjNG1GKu4"
  },
  {
    id: "2005",
    titulo: "Black Mirror",
    anioLanzamiento: 2011,
    descripcion: "Black Mirror presenta una serie de historias independientes que exploran los aspectos oscuros y perturbadores de la tecnología y la sociedad moderna. Cada episodio ofrece una visión distópica y reflexiva del futuro cercano, llevando al espectador a cuestionar la influencia de la tecnología en nuestras vidas y las posibles consecuencias de nuestras acciones. Con su estilo único y narrativa innovadora, Black Mirror es una provocativa antología que deja una impresión duradera en la audiencia.",
    tipo: "serie",
    url: "https://www.elespectadorimaginario.com/wp-content/webpc-passthru.php?src=http://www.elespectadorimaginario.com/wp-content/uploads/Black-Mirror-temporada-4.jpg&nocache=1",
    calificacion: 8.8,
    genero: ["Drama", "Sci-Fi", "Thriller"],
    duracion: "1h 3min",
    trailer: "rqJfoH1vfOg"
  },
  {
    id: "2006",
    titulo: "Sherlock",
    anioLanzamiento: 2010,
    descripcion: "Un moderno Sherlock Holmes resuelve casos intrigantes junto a su compañero, el Dr. Watson. Esta serie ofrece una mirada contemporánea al icónico detective y su aguda capacidad para resolver misterios aparentemente imposibles. Sherlock combina una narrativa inteligente, una excelente caracterización y un enfoque visualmente atractivo para sumergir a los espectadores en la mente brillante y compleja de uno de los personajes literarios más queridos de todos los tiempos.",
    tipo: "serie",
    url: "https://m.media-amazon.com/images/M/MV5BMWEzNTFlMTQtMzhjOS00MzQ1LWJjNjgtY2RhMjFhYjQwYjIzXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_FMjpg_UX1000_.jpg",
    calificacion: 9.1,
    genero: ["Crimen", "Drama", "Misterio"],
    duracion: "1h 28min",
    trailer: "iKUzhzustok"
  },
  {
    id: "2007",
    titulo: "The Mandalorian",
    anioLanzamiento: 2019,
    descripcion: "En las fronteras de la galaxia, lejos de la autoridad de la Nueva República, un cazarrecompensas conocido como The Mandalorian se embarca en aventuras emocionantes y peligrosas. Ambientada en el universo de Star Wars, esta serie presenta una historia épica y emocionante que sigue las hazañas de un solitario guerrero y su inesperado encuentro con un enigmático ser conocido como Baby Yoda. The Mandalorian ha cautivado a los fanáticos con su acción emocionante y su conexión con el legado de Star Wars.",
    tipo: "serie",
    url: "https://www.dodmagazine.es/wp-content/uploads/2023/01/the-mandalorian-temporada-3-star-wars.jpg",
    calificacion: 8.8,
    genero: ["Acción", "Aventura", "Ciencia ficción"],
    duracion: "40min",
    trailer: "IqZ48OcUHD8"
  },
  {
    id: "2008",
    titulo: "Peaky Blinders",
    anioLanzamiento: 2013,
    descripcion: "En las calles de Birmingham, una familia de gánsteres asciende al poder en el mundo del crimen organizado después de la Primera Guerra Mundial. Peaky Blinders ofrece una inmersión en el submundo de la delincuencia de los años 20, con personajes complejos y bien desarrollados que luchan por el poder y la supervivencia en un mundo peligroso y violento. Con su estilo distintivo y una narrativa absorbente, la serie ha recibido elogios por su actuación y su retrato atmosférico de la época.",
    tipo: "serie",
    url: "https://starsmydestination.files.wordpress.com/2022/06/peaky-blinders-t6.jpg",
    calificacion: 8.8,
    genero: ["Crimen", "Drama"],
    duracion: "1h",
    trailer: "oVzVdvGIC7U"
  },
  {
    id: "2009",
    titulo: "The Witcher",
    anioLanzamiento: 2019,
    descripcion: "En un mundo lleno de monstruos y seres sobrenaturales, un cazador de monstruos conocido como Geralt de Rivia lucha por encontrar su lugar en una sociedad donde los humanos son a menudo más peligrosos que las bestias. Basada en la serie de libros y videojuegos, The Witcher presenta una mezcla de acción, aventura y fantasía, con una narrativa no lineal que explora el destino entrelazado de sus protagonistas. Con su tono oscuro y su enfoque en la moralidad ambigua, la serie ha ganado una base de fanáticos apasionada.",
    tipo: "serie",
    url: "https://sm.ign.com/t/ign_latam/gallery/t/the-witche/the-witcher-season-3-first-look-images_qmt8.600.jpg",
    calificacion: 8.2,
    genero: ["Acción", "Aventura", "Fantasía"],
    duracion: "59min",
    trailer: "ETY44yszyNc"
  },
  {
    id: "2010",
    titulo: "La Casa de Papel",
    anioLanzamiento: 2017,
    descripcion: "Un grupo de criminales planea y ejecuta audaces atracos a la Fábrica Nacional de Moneda y Timbre de España. La Casa de Papel es un emocionante thriller de atracos que sigue las intrincadas estrategias y dramáticas tensiones entre los delincuentes y la policía. Con personajes carismáticos y giros sorprendentes, la serie ha capturado la atención del público global con su intensidad y su hábil construcción de suspenso.",
    tipo: "serie",
    url: "https://media.revistagq.com/photos/5e941e89d39d4700080d7e2b/master/w_1200,h_1502,c_limit/la-casa-de-papel.jpg",
    calificacion: 8.5,
    genero: ["Acción", "Crimen", "Drama"],
    duracion: "1h 10min",
    trailer: "3y-6iaveY6c"
  },
  {
    id: "2011",
    titulo: "Narcos",
    anioLanzamiento: 2015,
    descripcion: "Basada en hechos reales, Narcos cuenta la historia del auge y caída del narcotraficante colombiano Pablo Escobar y los cárteles de drogas en Colombia. Con una mirada cruda y realista al mundo del tráfico de drogas y el juego político, la serie ofrece una narrativa convincente y actuaciones destacadas que han resonado con el público. Narcos es un retrato fascinante y a menudo desgarrador de la guerra contra las drogas y sus devastadoras consecuencias.",
    tipo: "serie",
    url: "https://es.web.img3.acsta.net/pictures/15/07/29/14/33/086520.jpg",
    calificacion: 8.8,
    genero: ["Biografía", "Crimen", "Drama"],
    duracion: "49min",
    trailer: "xl8zdCY-abw"
  },
  {
    id: "2012",
    titulo: "The Simpsons",
    anioLanzamiento: 1989,
    descripcion: "The Simpsons es una serie de animación que ha conquistado al público desde 1989. Esta familia amarilla, integrada por Homero, Marge, Bart, Lisa y Maggie, vive divertidas y alocadas aventuras en la pintoresca ciudad de Springfield. Con su peculiar humor satírico, la serie ha sido aclamada por su sátira social y su capacidad para reflejar aspectos de la cultura popular. Cada episodio se sumerge en situaciones cómicas y extravagantes, mientras que los personajes icónicos y las travesuras de Bart y su padre Homero se han convertido en parte de la cultura pop mundial.",
    tipo: "serie",
    url: "https://images.justwatch.com/poster/301071430/s592/los-simpson",
    calificacion: 8.6,
    genero: ["Animación", "Comedia"],
    duracion: "1h",
    trailer: "_jgYEYERYFQ"
  },
  {
    id: "2013",
    titulo: "Chernobyl",
    anioLanzamiento: 2019,
    descripcion: "Chernobyl es una miniserie dramática que ofrece una intensa dramatización de los eventos que llevaron al desastre nuclear de Chernobyl en 1986. La serie se sumerge en el accidente en la central nuclear de Chernobyl en la Unión Soviética, explorando los errores humanos y el encubrimiento gubernamental que condujeron a una de las peores catástrofes nucleares de la historia. A través de una narrativa conmovedora y actuaciones impactantes, Chernobyl ofrece una visión desgarradora de las consecuencias devastadoras y el heroísmo de quienes enfrentaron la tragedia.",
    tipo: "serie",
    url: "https://pbs.twimg.com/media/FcjIGAhXwAA3MTJ?format=jpg&name=4096x4096",
    calificacion: 9.4,
    genero: ["Drama", "Historia", "Suspense"],
    duracion: "1h 0min",
    trailer: "s9APLXM9Ei8"
  },
  {
    id: "2014",
    titulo: "The Good Doctor",
    anioLanzamiento: 2017,
    descripcion: "The Good Doctor sigue la historia de Shaun Murphy, un joven cirujano con autismo y síndrome de Savant, que se une a un prestigioso hospital para practicar medicina. A pesar de las dudas y prejuicios de sus colegas, Shaun demuestra sus habilidades sobresalientes y su enfoque único para resolver complejos casos médicos. La serie explora temas de aceptación, empatía y superación personal, mientras Shaun se enfrenta a los desafíos de la vida profesional y personal en el mundo de la medicina.",
    tipo: "serie",
    url: "https://www.lavanguardia.com/peliculas-series/images/serie/poster/2017/9/w1280/eCvGVqmxXcNvLMJxLAJeBZ2cUnM.jpg",
    calificacion: 8.2,
    genero: ["Drama", "Médico"],
    duracion: "43min",
    trailer: "lnY9FWUTY84"
  },
  {
    id: "2015",
    titulo: "Rick and Morty",
    anioLanzamiento: 2013,
    descripcion: "Rick and Morty es una serie de animación con un estilo único y excéntrico que sigue las aventuras de Rick Sanchez, un científico alcohólico y excéntrico, y su nieto, Morty, un joven inexperto. Juntos, se embarcan en emocionantes y alocadas aventuras intergalácticas y dimensionales, enfrentando peligros y situaciones absurdas. La serie combina elementos de ciencia ficción, comedia negra y humor surrealista, y ha ganado popularidad por su ingenio, sátira y personajes memorables.",
    tipo: "serie",
    url: "https://es.web.img3.acsta.net/pictures/18/10/31/17/34/2348073.jpg",
    calificacion: 9.2,
    genero: ["Animación", "Aventura", "Comedia"],
    duracion: "23min",
    trailer: "E8cXKMR9a1Q"
  },
  {
    id: "2016",
    titulo: "Criminal Minds",
    anioLanzamiento: 2005,
    descripcion: "Criminal Minds sigue las investigaciones de un equipo de analistas del FBI especializados en resolver casos criminales complejos. Utilizando técnicas de perfilación, estudian las mentes de los asesinos en serie para anticipar sus movimientos y atraparlos antes de que vuelvan a atacar. La serie explora tanto los aspectos oscuros de la psicología humana como el arduo trabajo de los agentes encargados de proteger a la sociedad de los criminales más peligrosos.",
    tipo: "serie",
    url: "https://es.web.img2.acsta.net/pictures/14/02/14/13/31/367985.jpg",
    calificacion: 8.1,
    genero: ["Crimen", "Drama", "Misterio"],
    duracion: "42min",
    trailer: "R9qYmGXDX2M"
  },
  {
    id: "2017",
    titulo: "Grey's Anatomy",
    anioLanzamiento: 2005,
    descripcion: "Grey's Anatomy se desarrolla en el Hospital Grey Sloan Memorial y sigue a un grupo de jóvenes médicos que inician su carrera profesional enfrentando desafíos personales y profesionales. La serie se adentra en la vida del personal médico, sus relaciones y luchas, mientras atienden a pacientes con diversos problemas médicos. Con un enfoque en el drama y el romance, la serie ha cautivado a la audiencia con sus emocionantes tramas y giros inesperados.",
    tipo: "serie",
    url: "https://mx.web.img3.acsta.net/pictures/22/10/06/21/38/5529680.jpg",
    calificacion: 7.6,
    genero: ["Drama", "Romance"],
    duracion: "43min",
    trailer: "d78kuSX8MbM"
  },
  {
    id: "2018",
    titulo: "S.W.A.T",
    anioLanzamiento: 2017,
    descripcion: "S.W.A.T narra las misiones de un equipo de fuerzas especiales del departamento de policía de Los Ángeles, quienes se enfrentan a delitos de alto riesgo y crisis de rehenes. La serie muestra la preparación y valentía de estos agentes mientras se enfrentan a situaciones peligrosas y mantienen la calma bajo presión. A través de emocionantes escenas de acción, la serie explora el impacto emocional que el trabajo policial tiene en la vida personal de los miembros del equipo.",
    tipo: "serie",
    url: "https://www.dvdplanetstore.pk/wp-content/uploads/2017/12/am7NOjx56BpJOh1yFy6P70WmuTb.jpg",
    calificacion: 6.7,
    genero: ["Acción", "Aventura", "Crimen"],
    duracion: "43min",
    trailer: "MvSaUudnUes"

  },
  {
    id: "2019",
    titulo: "Hawaii Five-0",
    anioLanzamiento: 2010,
    descripcion: "Hawaii Five-0 sigue a un equipo de élite de la policía de Hawái mientras combate el crimen y lucha contra el mal en las hermosas islas de Hawái. A lo largo de la serie, los agentes se enfrentan a casos complejos que involucran crimen organizado, tráfico de drogas y amenazas a la seguridad nacional. Además de la emoción de las operaciones policiales, la serie también muestra los vínculos entre los miembros del equipo y su dedicación para proteger su hogar.",
    tipo: "serie",
    url: "https://images.justwatch.com/poster/148069656/s332/temporada-10",
    calificacion: 7.3,
    genero: ["Acción", "Crimen", "Drama"],
    duracion: "42min",
    trailer: "GUM68_HgtIA"
  },
  {
    id: "2020",
    titulo: "NCIS: Los Ángeles",
    anioLanzamiento: 2009,
    descripcion: "En NCIS: Los Ángeles, un equipo de agentes encubiertos del NCIS trabaja en Los Ángeles para detener amenazas a la seguridad nacional. La serie se centra en operaciones encubiertas, espionaje y la lucha contra el crimen a nivel internacional. Los agentes utilizan sus habilidades especiales y su ingenio para resolver complejos casos, enfrentando peligros y desafíos en su lucha por proteger al país.",
    tipo: "serie",
    url: "https://m.media-amazon.com/images/M/MV5BMGQzNGIzNmEtNWE3ZS00OTUyLTg3YTEtMDY3NDViZWE0YWY1XkEyXkFqcGdeQXVyNjg4NzAyOTA@._V1_.jpg",
    calificacion: 6.7,
    genero: ["Acción", "Crimen", "Drama"],
    duracion: "43min",
    trailer: "f1-OHMyJWN8"
  },
  {
    id: "2021",
    titulo: "NCIS",
    anioLanzamiento: 2003,
    descripcion: "NCIS sigue las investigaciones de un equipo de agentes especiales del NCIS mientras resuelven crímenes relacionados con la Marina de los Estados Unidos y el Cuerpo de Marines. La serie se adentra en el mundo de la investigación criminal militar, abordando temas de patriotismo y lealtad. Con un enfoque en el drama y la acción, NCIS ha ganado popularidad por su emocionante narrativa y personajes carismáticos..",
    tipo: "serie",
    url: "https://m.media-amazon.com/images/M/MV5BYjVlMjZhYzYtOGQxNC00OTQxLTk2NzEtMWFmMmNhODA4YjYzXkEyXkFqcGdeQXVyNjQ3MDgwNjY@._V1_FMjpg_UX1000_.jpg",
    calificacion: 7.8,
    genero: ["Acción", "Crimen", "Drama"],
    duracion: "43min",
    trailer: "c327esqh9q0"
  },
  {
    id: "2022",
    titulo: "House M.D.",
    anioLanzamiento: 2004,
    descripcion: "House M.D. presenta al Dr. Gregory House, un brillante pero cínico médico, quien lidera un equipo de diagnóstico en un hospital universitario. La serie se centra en resolver misteriosos casos médicos que desafían a otros médicos. House utiliza su ingenio y un enfoque poco convencional para diagnosticar enfermedades raras y salvar vidas. La serie explora temas médicos complejos y la ética en la medicina..",
    tipo: "serie",
    url: "https://images.justwatch.com/poster/199979170/s332/temporada-8",
    calificacion: 8.7,
    genero: ["Drama", "Médico", "Misterio"],
    duracion: "44min",
    trailer: "MczMB8nU1sY"
  },
  {
    id: "2023",
    titulo: "Lucifer",
    anioLanzamiento: 2016,
    descripcion: "Lucifer sigue la historia de Lucifer Morningstar, el Diablo, quien abandona el Infierno y se retira a Los Ángeles, donde administra un club nocturno y ayuda a la policía a resolver crímenes. La serie combina elementos de crimen, drama y fantasía, explorando temas de redención, libre albedrío y la dualidad de la naturaleza humana. A través de su singular perspectiva, Lucifer enfrenta tanto los problemas del mundo mortal como su propio viaje emocional",
    tipo: "serie",
    url: "https://es.web.img3.acsta.net/pictures/17/07/19/14/29/555036.jpg?coixp=50&coiyp=37",
    calificacion: 8.1,
    genero: ["Crimen", "Drama", "Fantasía"],
    duracion: "43min",
    trailer: "lpFiEZ-4Vtc"
  },
  {
    id: "2024",
    titulo: "Línea de emergencia: 9-1-1",
    anioLanzamiento: 2018,
    descripcion: "9-1-1 ofrece una mirada intensa a la vida y carreras de quienes trabajan en la línea de emergencia 911, atendiendo llamadas de ayuda en situaciones críticas. La serie se centra en los desafíos que enfrentan los operadores, paramédicos, bomberos y policías mientras luchan contra el tiempo para salvar vidas y resolver situaciones peligrosas. Con una combinación de drama y acción, la serie muestra el heroísmo y la dedicación de quienes responden a las llamadas de emergencia.",
    tipo: "serie",
    url: "https://parecidas.com/img_es/movie/thumb/b5/45176.jpg",
    calificacion: 7.7,
    genero: ["Acción", "Drama", "Thriller"],
    duracion: "43min",
    trailer: "PBm3DcjQ62o"
  },
  {
    id: "2025",
    titulo: "El mundo oculto de Sabrina",
    anioLanzamiento: 2018,
    descripcion: "El mundo oculto de Sabrina sigue la vida de Sabrina Spellman, una joven mitad bruja y mitad mortal, mientras debe lidiar con su doble naturaleza y enfrentar fuerzas oscuras que amenazan su mundo. La serie combina elementos de drama, fantasía y terror, explorando temas de identidad, poder y el choque entre el mundo mágico y el mundo humano. A lo largo de la serie, Sabrina debe tomar decisiones difíciles y enfrentar desafíos sobrenaturales mientras busca su lugar en ambos mundos.",
    tipo: "serie",
    url: "https://mx.web.img3.acsta.net/pictures/18/09/22/02/56/2323749.jpg",
    calificacion: 7.5,
    genero: ["Drama", "Fantasía", "Terror"],
    duracion: "1h",
    trailer: "51fOujPcgIE"
  },
  {
    id: "2039",
    titulo: "Riverdale",
    anioLanzamiento: 2017,
    descripcion: "Riverdale tiene lugar en la aparentemente tranquila ciudad de Riverdale, donde un grupo de jóvenes se enfrenta a oscuros misterios y secretos mientras investigan crímenes. La serie explora la vida de Archie, Betty, Veronica y Jughead mientras lidian con problemas familiares, amoríos complicados y oscuros secretos que rodean a la ciudad. Con una mezcla de crimen, drama y misterio, Riverdale ha cautivado a la audiencia con su intriga y giros inesperados..",
    tipo: "serie",
    url: "https://es.web.img2.acsta.net/pictures/19/10/08/11/04/2148033.jpg",
    calificacion: 6.8,
    genero: ["Crimen", "Drama", "Misterio"],
    duracion: "45min",
    trailer: "HxtLlByaYTc"
  }

];

export { series }